### ISSUE TITLE
How can I get a thread number?

### ISSUE THREAD

**Issue by Naumych** [SimitTomar/wdio-cucumber-parallel-execution#12]
Hello. I need to run my tests in parallel, but I'm not able to use one user. It should use different users in one time. I need to know number of thread to use corresponding user. How can I get a thread number?

**Comment by SimitTomar** [comment]
The Number of threads are defined by WebdriverIO's **maxInstance** attribute, specified in the Config File. Handling of Multiple Users should be done through your Automation Scripts. This module simply creates multiple Feature File out of a single FF which then get picked up by WebdriverIO's test runner. It has nothing to do with the User Vs Thread Allocation
