### ISSUE TITLE
stack-chain issue with version 7+ of wdio

### ISSUE THREAD

**Issue by alexwalker1993** [SimitTomar/wdio-cucumber-parallel-execution#18]
Due to cucumber changing from cucumber to @cucumber/cucumber and updating there version of stack-chain this library now causes an error: Conflicting version of stack-chain found

This is because this library pulls in a version of cucumber using stack-chain 1.3.7
The newer versions of cucumber use stack-chain 2.0.0

I tried to fork and update the versions myself but it didn't work so could really do with some help on this

**Comment by yunj** [comment]
Hi @alexwalker1993, just wondering if you're still having the issue? I use `@wdio/cli` and `@wdio/cucumber-framework` with version `7.11.0`, but I don't have this issue.

**Comment by alexwalker1993** [comment]
I've managed to work around this now but I'm not actually sure how I fixed it I have a feeling it may have been some of the dependencies we have removed that was causing the original problem
