### ISSUE TITLE
How do you execute the specific number of parallel execution ?

### ISSUE THREAD

**Issue by syamphaneendra** [SimitTomar/wdio-cucumber-parallel-execution#21]
How do you execute the specific number of parallel execution ? For example if I have 3 feature files having 10 scenarios, How can I execute them with only 5 parallel threads ?

**Comment by anirudhkumarvyas** [comment]
Hi Syamphaneendra,
You can use **wdio-cucumber-parallel-execution** and configure the **maxInstances** property to 5 in your wdio config.

Regards,
Anirudh Vyas

**Comment by syamphaneendra** [comment]
ok, Thank you

**Comment by anirudhkumarvyas** [comment]
I hope your issue is resolved so closing this.
