### ISSUE TITLE
Could you provide a more detailed setup?

### ISSUE THREAD

**Issue by Farmijo** [SimitTomar/wdio-cucumber-parallel-execution#7]
Currently, i'm setting up the capability like this:
```
  capabilities: [{
    maxInstances: 15,
    platformName: 'ANY',
    browserName: 'chrome',
  },
  [wdioParallel.performSetup({
    sourceSpecDirectory: "./src/features/TR/AntiFraud",
    tmpSpecDirectory: "./src/featuresTemp",
    cleanTmpSpecDirectory: true
  })]
]
```

It is crashing me with the following error:

```
/Users/francisco.armijo/Desktop/repos/letgo-b2b-tests/node_modules/@wdio/cli/build/utils.js:95
    runner = Object.values(caps).length === 0 || Object.values(caps).some(cap => !cap.capabilities) ? 'undefined' : 'MultiRemote';
```

Not sure how should I define this capability.

**Comment by SimitTomar** [comment]
@Farmijo ,

You don't need to set it within the capabilities block. Also this has been tested with webdriverio V4. If your are using V4 then you can use it like below:

const wdioParallel = require('wdio-cucumber-parallel-execution');

wdioParallel.performSetup({
    sourceSpecDirectory: './src/features/TR/AntiFraud',
    tmpSpecDirectory: './src/featuresTemp',
    cleanTmpSpecDirectory: true
});

exports.config = {
// Runner Configuration like capabilities and all go here
}
